module.exports = {
  ...require('./AuthPayload'),
  ...require('./Mutation'),
  ...require('./Post'),
  ...require('./Query'),
  ...require('./Subscription'),
  ...require('./User'),
  ...require('./Business'),
  ...require('./Branch'),
  ...require('./Service'),
  ...require('./Employee'),
  ...require('./Booking'),
  ...require('./AvailabilityItem'),
  ...require('./VacationsItem'),
  ...require('./EmployeeAvailableTime'),
}
